name: Upload Node.js 10 and 12 tool cache
on: push
jobs:
  upload_tool_cache:
    runs-on: ubuntu-22.04
    steps:
      - name: Clear any existing tool cache
        run: |
          mv "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old"
          mkdir -p "${{ runner.tool_cache }}"
      - name: Setup Node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Setup Java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Setup Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          check-latest: true
      - name: Setup Hugo 0.110.0
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.110.0'
          extended: true
      - name: Archive tool cache
        run: |
          cd "${{ runner.tool_cache }}"
          tar -czf tool_cache.tar.gz *
      - name: Upload tool cache artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{runner.tool_cache}}/tool_cache.tar.gz
